name: storage_client
description: Dart client library to interact with Supabase Storage.
version: 0.0.6+2
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/storage-dart'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  mime: ^1.0.0

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.16.4
  lints: ^1.0.1
